### ISSUE TITLE
MacOS version is corrupted & won't install

### ISSUE THREAD

**Issue by recordandmix** [DMXCore/Pico2ReMapper-Public#1]
When I download the MacOS version from the repo, I right-clicked on it and selected "open", as suggested.  Rather than open as an app, it opens as a (garbled) text document in Text Edit.  Is there an alternate way to build the app, perhaps in Xcode?

**Comment by HakanL** [comment]
Unfortunately it can't be compiled in Xcode as the source code is in C#, but the issue is that the binary isn't marked as an executable, which you can fix:
Launch Terminal, navigate to the folder with the application and enter this command `chmod +x DmxRemapperConfig`. Then you should be able to run it. It seems that the flag didn't get saved in the zip file, I may have to look at a different way to package it.

**Comment by recordandmix** [comment]
fixed!  Thanks for the quick response.

**Comment by HakanL** [comment]
Great! And just let me know if you need any help or any new features!
